"""test_prince

Revision ID: 2607d2cf9ea0
Revises: 0d7bd3ecdefd
Create Date: 2025-11-03 22:01:12.553186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2607d2cf9ea0'
down_revision: Union[str, Sequence[str], None] = '0d7bd3ecdefd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_of_asset', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location_of_asset')
    # ### end Alembic commands ###
