"""initial

Revision ID: 52d3366fe580
Revises: 
Create Date: 2025-11-24 18:23:00.077718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d3366fe580'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solar_farms',
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('farm_name', sa.String(length=255), nullable=False),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('total_capacity_kw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('available_panels', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('land_lease_start_date', sa.Date(), nullable=True),
    sa.Column('land_lease_end_date', sa.Date(), nullable=True),
    sa.Column('land_owner', sa.String(length=255), nullable=True),
    sa.Column('operational_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('land_lease_start_date IS NULL OR land_lease_end_date IS NULL OR land_lease_start_date <= land_lease_end_date', name='check_lease_dates'),
    sa.PrimaryKeyConstraint('farm_id')
    )
    op.create_index(op.f('ix_solar_farms_farm_id'), 'solar_farms', ['farm_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('registration_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('account_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('customer_consumption',
    sa.Column('consumption_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('energy_consumed_kwh', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('consumption_id')
    )
    op.create_index(op.f('ix_customer_consumption_consumption_id'), 'customer_consumption', ['consumption_id'], unique=False)
    op.create_index('ix_customer_consumption_customer_month', 'customer_consumption', ['customer_id', 'month'], unique=False)
    op.create_table('energy_credits',
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('billing_period_start', sa.Date(), nullable=False),
    sa.Column('billing_period_end', sa.Date(), nullable=False),
    sa.Column('total_generated_kwh', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_consumed_kwh', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('billing_period_start <= billing_period_end', name='check_billing_period_dates'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('credit_id')
    )
    op.create_index(op.f('ix_energy_credits_credit_id'), 'energy_credits', ['credit_id'], unique=False)
    op.create_index('ix_energy_credits_customer_billing', 'energy_credits', ['customer_id', 'billing_period_start'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.create_table('solar_panels',
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('panel_serial_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('capacity_watts', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('warranty_expiry_date', sa.Date(), nullable=True),
    sa.Column('panel_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['solar_farms.farm_id'], ),
    sa.PrimaryKeyConstraint('panel_id'),
    sa.UniqueConstraint('panel_serial_number')
    )
    op.create_index(op.f('ix_solar_panels_panel_id'), 'solar_panels', ['panel_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    op.create_table('energy_generation',
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('energy_generated_kwh', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('voltage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('current', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('efficiency_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['solar_panels.panel_id'], ),
    sa.PrimaryKeyConstraint('generation_id')
    )
    op.create_index(op.f('ix_energy_generation_generation_id'), 'energy_generation', ['generation_id'], unique=False)
    op.create_index('ix_energy_generation_panel_timestamp', 'energy_generation', ['panel_id', 'timestamp'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_type', sa.String(length=50), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('scheduled_date IS NULL OR completed_date IS NULL OR scheduled_date <= completed_date', name='check_maintenance_dates'),
    sa.ForeignKeyConstraint(['farm_id'], ['solar_farms.farm_id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['solar_panels.panel_id'], ),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    op.create_index(op.f('ix_maintenance_records_maintenance_id'), 'maintenance_records', ['maintenance_id'], unique=False)
    op.create_table('panel_ownership',
    sa.Column('ownership_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('panel_id', sa.Integer(), nullable=True),
    sa.Column('ownership_type', sa.String(length=20), nullable=True),
    sa.Column('ownership_status', sa.String(length=20), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lease_start_date', sa.Date(), nullable=True),
    sa.Column('lease_end_date', sa.Date(), nullable=True),
    sa.Column('monthly_lease_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lease_start_date IS NULL OR lease_end_date IS NULL OR lease_start_date <= lease_end_date', name='check_ownership_lease_dates'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['solar_panels.panel_id'], ),
    sa.PrimaryKeyConstraint('ownership_id')
    )
    op.create_index(op.f('ix_panel_ownership_ownership_id'), 'panel_ownership', ['ownership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_panel_ownership_ownership_id'), table_name='panel_ownership')
    op.drop_table('panel_ownership')
    op.drop_index(op.f('ix_maintenance_records_maintenance_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index('ix_energy_generation_panel_timestamp', table_name='energy_generation')
    op.drop_index(op.f('ix_energy_generation_generation_id'), table_name='energy_generation')
    op.drop_table('energy_generation')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_solar_panels_panel_id'), table_name='solar_panels')
    op.drop_table('solar_panels')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_energy_credits_customer_billing', table_name='energy_credits')
    op.drop_index(op.f('ix_energy_credits_credit_id'), table_name='energy_credits')
    op.drop_table('energy_credits')
    op.drop_index('ix_customer_consumption_customer_month', table_name='customer_consumption')
    op.drop_index(op.f('ix_customer_consumption_consumption_id'), table_name='customer_consumption')
    op.drop_table('customer_consumption')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_solar_farms_farm_id'), table_name='solar_farms')
    op.drop_table('solar_farms')
    # ### end Alembic commands ###
