"""Add supertokens_user_id to User model

Revision ID: ce8f93d3efe7
Revises: 2607d2cf9ea0
Create Date: 2025-11-04 11:18:51.103978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8f93d3efe7'
down_revision: Union[str, Sequence[str], None] = '2607d2cf9ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supertokens_user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_supertokens_user_id'), 'users', ['supertokens_user_id'], unique=True)
    op.drop_column('users', 'location_of_asset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_of_asset', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_supertokens_user_id'), table_name='users')
    op.drop_column('users', 'supertokens_user_id')
    # ### end Alembic commands ###
